<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-WorkerService-e55c8607-fd44-40e1-8baa-4ede5d3c9152</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2"/>
    </ItemGroup>

    <ItemGroup>    
      <ProjectReference Include="..\..\src\Softoverse.EventBus.InMemory\Softoverse.EventBus.InMemory.csproj" />
      <ProjectReference Include="..\..\tests\EventBus.InMemory.Tests\EventBus.InMemory.Tests.csproj" />
    </ItemGroup>
</Project>
